MantenimientoPersonas/Controllers/PersonaController.cs
using MantenimientoPersonas.Constants;
using MantenimientoPersonas.Data;
using MantenimientoPersonas.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace MantenimientoPersonas.Controllers
{
    [Authorize]
    public class PersonaController : Controller
    {
        private readonly CRUDContext? _context;
        private readonly ILogger<PersonaController> _logger;
        private readonly IAuthorizationService _authorizationService;

        public PersonaController(CRUDContext context, ILogger<PersonaController> logger, IAuthorizationService authorizationService)
        {
            _context = context;
            _logger = logger;
            _authorizationService = authorizationService;
        }
        [Authorize("Permisos.Personas.Ver")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize("Permisos.Personas.Ver")]
        [HttpGet]
        public JsonResult ObtenerPersonaPorId(int id)
        {
            try
            {
                var persona = _context.Personas.Find(id);

                if (persona != null)
                {
                    var prids = _context.Personas
                                        .Where(persona => persona.persona_id == id)
                                        .SelectMany(persona => persona.personas_relacionadas.Select(personarelacionada => personarelacionada.persona_relacionada_id))
                                        .ToArray();

                    persona.pr_id = prids;

                    // Retornar un JSON con la persona relacionada y sus roles_id
                    return Json(persona);
                }
                return Json(persona);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }
        [Authorize("Permisos.Personas.Ver")]

        [HttpGet]

        public JsonResult ObtenerPersonaPorNumeroDocumento(string ndocumento)
        {
            try
            {
                bool personaExiste = _context.Personas.Any(p => p.numero_documento == ndocumento);

                if (personaExiste)
                {
                    return Json(new { message = 1 });
                }
                return Json(new { message = 0 });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }
        [Authorize("Permisos.Personas.Ver")]

        [HttpGet]
        public async Task<JsonResult> ObtenerPersonas()
        {
            var personas = _context.Personas.Where(p => p.estado_activo == true).ToList();
            var puedeEditar = (await _authorizationService.AuthorizeAsync(User, "Permisos.Personas.Editar")).Succeeded;
            var puedeEliminar = (await _authorizationService.AuthorizeAsync(User, "Permisos.Personas.Eliminar")).Succeeded;
            var puedeCrear = (await _authorizationService.AuthorizeAsync(User, "Permisos.Personas.Crear")).Succeeded;

            var resultado = new
            {
                Personas = personas,
                PuedeEditar = puedeEditar,
                PuedeEliminar = puedeEliminar,
                PuedeCrear = puedeCrear
            };

            return Json(resultado);
        }
        [Authorize("Permisos.Personas.Crear")]

        [HttpPost]
        public JsonResult AgregarPersona(PersonaModel persona)
        {
            
            if (ModelState.IsValid)
            {
                _context.Personas.Add(persona);
                _context.SaveChanges();
                if (persona.pr_id != null)
                {
                    var personasrelacionadas = _context.PersonasRelacionadas.Where(pr => persona.pr_id.Contains(pr.persona_relacionada_id)).ToList();
                    foreach (var personarelacionada in personasrelacionadas)
                    {
                        personarelacionada.persona_id = persona.persona_id;
                    }

                    _context.SaveChanges();
                }

                return Json(new { success = true, message = 1 });
            }
            else
            {
                return Json(new { success = false, message = 0 });
            }



        }
        [Authorize("Permisos.Personas.Editar")]

        [HttpPut]
        public JsonResult ActualizarPersona(PersonaModel personat)
        {
            if (ModelState.IsValid)
            {


                if (personat.pr_id != null)
                {
                    
                    var persona = _context.Personas.Include(p => p.personas_relacionadas).FirstOrDefault(p => p.persona_id == personat.persona_id);
                    if (persona == null)
                    {
                        return Json(new { success = false, message = 0 });
                    }
                    var currentpersonasrelacionadas = persona.personas_relacionadas.Select(pr => pr.persona_relacionada_id).ToList();
                    var personasrelacionadasToAdd = personat.pr_id.Except(currentpersonasrelacionadas).ToList();

                    var personasrelacionadasToRemove = currentpersonasrelacionadas.Except(personat.pr_id).ToList();
                    if (personasrelacionadasToRemove.Any())
                    {
                        var personasrelacionadas = _context.PersonasRelacionadas.Where(pr => personasrelacionadasToRemove.Contains(pr.persona_relacionada_id)).ToList();
                        foreach (var personarelacionada in personasrelacionadas)
                        {
                            personarelacionada.persona_id = null;
                        }
                    }



                    if (personasrelacionadasToAdd.Any())
                    {
                        var personasrelacionadas = _context.PersonasRelacionadas.Where(pr => personasrelacionadasToAdd.Contains(pr.persona_relacionada_id)).ToList();
                        foreach (var personarelacionada in personasrelacionadas)
                        {
                            personarelacionada.persona_id = persona.persona_id;
                        }
                    }
                    persona.tipo_documento = personat.tipo_documento;
                    persona.numero_documento = personat.numero_documento;
                    persona.primer_nombre = personat.primer_nombre;
                    persona.segundo_nombre = personat.segundo_nombre;
                    persona.primer_apellido = personat.primer_apellido;
                    persona.segundo_apellido = personat.segundo_apellido;
                    persona.numero_telefono = personat.numero_telefono;
                    persona.tipo_telefono = personat.tipo_telefono;
                    persona.mayoria_edad = personat.mayoria_edad;
                    persona.genero = personat.genero;
                    persona.estado_activo = personat.estado_activo;
                    _context.Personas.Update(persona);
                }
                else
                {
                    int[] ints = { };
                    var persona = _context.Personas.Include(p => p.personas_relacionadas).FirstOrDefault(p => p.persona_id == personat.persona_id);
                    if (persona == null)
                    {
                        return Json(new { success = false, message = 0 });
                    }
                    var currentpersonasrelacionadas = persona.personas_relacionadas.Select(pr => pr.persona_relacionada_id).ToList();
                    var personasrelacionadasToAdd = ints.Except(currentpersonasrelacionadas).ToList();

                    var personasrelacionadasToRemove = currentpersonasrelacionadas.Except(ints).ToList();
                    if (personasrelacionadasToRemove.Any())
                    {
                        var personasrelacionadas = _context.PersonasRelacionadas.Where(pr => personasrelacionadasToRemove.Contains(pr.persona_relacionada_id)).ToList();
                        foreach (var personarelacionada in personasrelacionadas)
                        {
                            personarelacionada.persona_id = null;
                        }
                    }



                    if (personasrelacionadasToAdd.Any())
                    {
                        var personasrelacionadas = _context.PersonasRelacionadas.Where(pr => personasrelacionadasToAdd.Contains(pr.persona_relacionada_id)).ToList();
                        foreach (var personarelacionada in personasrelacionadas)
                        {
                            personarelacionada.persona_id = persona.persona_id;
                        }
                    }
                    persona.tipo_documento = personat.tipo_documento;
                    persona.numero_documento = personat.numero_documento;
                    persona.primer_nombre = personat.primer_nombre;
                    persona.segundo_nombre = personat.segundo_nombre;
                    persona.primer_apellido = personat.primer_apellido;
                    persona.segundo_apellido = personat.segundo_apellido;
                    persona.numero_telefono = personat.numero_telefono;
                    persona.tipo_telefono = personat.tipo_telefono;
                    persona.mayoria_edad = personat.mayoria_edad;
                    persona.genero = personat.genero;
                    persona.estado_activo = personat.estado_activo;
                    _context.Personas.Update(persona);
                }


                _context.SaveChanges();

                return Json(new { success = true, message = 1 });
            }
            else
            {
                return Json(new { success = true, message = 0 });
            }
        }
        [Authorize("Permisos.Personas.Eliminar")]

        [HttpDelete]

MantenimientoPersonas/Controllers/RolController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MantenimientoPersonas.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class RolController : Controller
    {
        private readonly RoleManager<IdentityRole> _rolManager;

        public RolController(RoleManager<IdentityRole> rolManager)
        {
            _rolManager = rolManager;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var roles = await _rolManager.Roles.ToListAsync();
            return View(roles);
        }
        [HttpPost]
        public async Task<IActionResult> AgregarRol(string nombreRol)
        {
            if (nombreRol != null)
            {
                await _rolManager.CreateAsync(new IdentityRole(nombreRol.Trim()));
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> EliminarRol(string rolId)
        {

            if (rolId != null)
            {
                var rol = _rolManager.FindByIdAsync(rolId).Result;
                if (rol != null)
                {
                    await _rolManager.DeleteAsync(rol);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

MantenimientoPersonas/Controllers/UserController.cs
using MantenimientoPersonas.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace MantenimientoPersonas.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UserController : Controller
    {
        private readonly UserManager<UserModel> _userManager;
        public UserController(UserManager<UserModel> userManager)
        {
            _userManager = userManager;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var allUsersExceptCurrentUser = await _userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
            return View(allUsersExceptCurrentUser);
        }
        [HttpPost]
        public async Task<IActionResult> EliminarUsuario(string userId)
        {

            if (userId != null)
            {
                var user = _userManager.FindByIdAsync(userId).Result;
                if (user != null)
                {
                    await _userManager.DeleteAsync(user);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

MantenimientoPersonas/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@using MantenimientoPersonas.Constants
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MantenimientoPersonas.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-5.2.3-dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/select2/select2.css" rel="stylesheet" />
    <link href="~/lib/select2/select2-bootstrap-5-theme.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/datatables.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/jquery-confirm/css/jquery-confirm.css" rel="stylesheet" asp-append-version="true" />
</head>
<body class="bg-gray-100 dark:bg-gray-900">
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <img src="~/resources/images/logodotnet.png" width="40" height="40" class="bi  me-2" />
                <span class="fs-4">ASP.NET Core MVC</span>
            </a>

            <ul class="nav nav-pills">
                <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Inicio</a></li>
                @if ((AuthorizationService.AuthorizeAsync(User, Permisos.Personas.Ver)).Result.Succeeded)
                {
                    <li class="nav-item">
                        <a asp-controller="Persona" asp-action="Index" class="nav-link" aria-current="page">Personas</a>
                    </li>
                }
                @if ((AuthorizationService.AuthorizeAsync(User, Permisos.PersonasRelacionadas.Ver)).Result.Succeeded)
                {
                    <li class="nav-item">
                        <a asp-controller="PersonaRelacionada" asp-action="Index" class="nav-link" aria-current="page">Personas Relacionadas</a>
                    </li>
                }

                @if ((AuthorizationService.AuthorizeAsync(User, Permisos.Usuarios.Ver)).Result.Succeeded)
                {
                    <li class="nav-item">
                        <a asp-controller="User" asp-action="Index" class="nav-link" aria-current="page">Usuarios</a>
                    </li>

                }
                @if ((AuthorizationService.AuthorizeAsync(User, Permisos.Roles.Ver)).Result.Succeeded)
                {
                    <li class="nav-item">
                        <a asp-controller="Rol" asp-action="Index" class="nav-link" aria-current="page">Roles</a>
                    </li>
                }
                &nbsp;
                <li class="nav-item"><a onclick="cerrarSesion();" type="button" class="nav-link" aria-current="page">Cerrar sesión</a></li>

            </ul>
        </header>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            <br /><br /><br /><br />
            <h2 class="text-center">@ViewData["TitleView"]</h2>
            <br />
            @RenderBody()
        </main>
    </div>

    <footer class="fixed bottom-0 left-0 z-20 w-full p-4 bg-white border-t border-gray-200 shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800 dark:border-gray-600">
        <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
            © 2024 - Mantenimiento de Personas - Elimelet Caraballo
        </span>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap-5.2.3-dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/select2/select2.full.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js" asp-append-version="true"></script>

    <script src="~/lib/input-mask/jquery.inputmask.min.js" asp-append-version="true"></script>
    <script src="~/lib/moment/moment.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/datatables.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-confirm/js/jquery-confirm.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/2d70f210f1.js" crossorigin="anonymous"></script>
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>