MantenimientoPersonas/Controllers/PermisoController.cs
using MantenimientoPersonas.Constants;
using MantenimientoPersonas.Helpers;
using MantenimientoPersonas.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;

namespace MantenimientoPersonas.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class PermisoController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public PermisoController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<ActionResult> Index(string roleId)
        {
            var model = new PermisoViewModel();
            var allPermiso = new List<RoleClaimsViewModel>();

            // Obtén todos los tipos de permisos automáticamente
            var permisoTypes = typeof(Permisos).GetNestedTypes(BindingFlags.Static | BindingFlags.Public);
            foreach (var permisoType in permisoTypes)
            {
                allPermiso.ObtenerPermisos(permisoType, roleId);
            }

            var role = await _roleManager.FindByIdAsync(roleId);
            model.RoleId = roleId;
            var claims = await _roleManager.GetClaimsAsync(role);

            var allClaimValues = allPermiso.Select(a => a.Value).ToList();
            var roleClaimValues = claims.Select(a => a.Value).ToList();
            var authorizedClaims = allClaimValues.Intersect(roleClaimValues).ToList();

            foreach (var permission in allPermiso)
            {
                if (authorizedClaims.Any(a => a == permission.Value))
                {
                    permission.Selected = true;
                }
            }

            model.RoleClaims = allPermiso;
            return View(model);
        }
        public async Task<IActionResult> Update(PermisoViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.RoleId);
            var claims = await _roleManager.GetClaimsAsync(role);
            foreach (var claim in claims)
            {
                await _roleManager.RemoveClaimAsync(role, claim);
            }
            var selectedClaims = model.RoleClaims.Where(a => a.Selected).ToList();
            foreach (var claim in selectedClaims)
            {
                await _roleManager.AgregarClaimPermiso(role, claim.Value);
            }
            return RedirectToAction("Index", new { roleId = model.RoleId });
        }
    }
}

MantenimientoPersonas/Controllers/RolController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MantenimientoPersonas.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class RolController : Controller
    {
        private readonly RoleManager<IdentityRole> _rolManager;

        public RolController(RoleManager<IdentityRole> rolManager)
        {
            _rolManager = rolManager;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var roles = await _rolManager.Roles.ToListAsync();
            return View(roles);
        }
        [HttpPost]
        public async Task<IActionResult> AgregarRol(string nombreRol)
        {
            if (nombreRol != null)
            {
                await _rolManager.CreateAsync(new IdentityRole(nombreRol.Trim()));
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> EliminarRol(string rolId)
        {

            if (rolId != null)
            {
                var rol = _rolManager.FindByIdAsync(rolId).Result;
                if (rol != null)
                {
                    await _rolManager.DeleteAsync(rol);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

MantenimientoPersonas/Views/Rol/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<IdentityRole>
<h1>Roles</h1>
<br />
<form method="post" asp-action="AgregarRol" asp-controller="Rol">
    <div class="input-group">
        <input name="nombreRol" class="form-control w-25">
        &nbsp;
        <span class="input-group-btn">
            <button class="btn btn-primary">Agregar nuevo rol</button>
        </span>
    </div>
</form>
<table class="table table-striped" id="roleTable">
    <thead>
        <tr>
            <th>
                Rol
            </th>
            <th>
                Id
            </th>
            <th style="width:10%">
                Acciones
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var role in Model)
        {
            <tr>
                <td>
                    @role.Name
                </td>
                <td>
                    @role.Id
                </td>
                <td class="text-right">
                    @if (role.Name != "Administrador")
                    {

                    <div class="btn-group">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Acción
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                        <form asp-action="EliminarRol" asp-controller="Rol" method="post">
                                            <input type="hidden" name="rolId" value="@role.Id" />
                                            <button type="submit" class="dropdown-item"><i class="fas fa-trash-alt"></i> Eliminar</button>
                                        </form>

                                </li>
                                <li>
                                        <a style='margin-right:16px' asp-controller="Permiso" asp-action="Index" asp-route-roleId="@role.Id" class="dropdown-item">
                                            <i class="fas fa-wrench"></i> Administrar permisos
                                        </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>