MantenimientoPersonas/Controllers/UserController.cs
using MantenimientoPersonas.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace MantenimientoPersonas.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UserController : Controller
    {
        private readonly UserManager<UserModel> _userManager;
        public UserController(UserManager<UserModel> userManager)
        {
            _userManager = userManager;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var allUsersExceptCurrentUser = await _userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
            return View(allUsersExceptCurrentUser);
        }
        [HttpPost]
        public async Task<IActionResult> EliminarUsuario(string userId)
        {

            if (userId != null)
            {
                var user = _userManager.FindByIdAsync(userId).Result;
                if (user != null)
                {
                    await _userManager.DeleteAsync(user);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

MantenimientoPersonas/Controllers/UserRolesController.cs
using MantenimientoPersonas.Constants;
using MantenimientoPersonas.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MantenimientoPersonas.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UserRolesController : Controller
    {
        private readonly SignInManager<UserModel> _signInManager;
        private readonly UserManager<UserModel> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IConfiguration _configuration;
        public UserRolesController(UserManager<UserModel> userManager, SignInManager<UserModel> signInManager, RoleManager<IdentityRole> roleManager, IConfiguration configuration)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _configuration = configuration;
        }
        public async Task<IActionResult> Index(string userId)
        {
            var viewModel = new List<UserRolesViewModel>();
            var user = await _userManager.FindByIdAsync(userId);
            foreach (var role in _roleManager.Roles.ToList())
            {
                var userRolesViewModel = new UserRolesViewModel
                {
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                viewModel.Add(userRolesViewModel);
            }
            var model = new ManageUserRolesViewModel()
            {
                UserId = userId,
                UserRoles = viewModel
            };
            return View(model);
        }
        public async Task<IActionResult> Update(string id, ManageUserRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            result = await _userManager.AddToRolesAsync(user, model.UserRoles.Where(x => x.Selected).Select(y => y.RoleName));
            var currentUser = await _userManager.GetUserAsync(User);
            await _signInManager.RefreshSignInAsync(currentUser);
            await Seeds.DefaultUsers.SembrarUsuarioAdministradorAsync(_userManager, _roleManager, _configuration["DefaultUser:Password"]);
            return RedirectToAction("Index", new { userId = id });
        }
    }
}

MantenimientoPersonas/Views/User/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<UserModel>
<style>
    .scrollable-div-u {
        height: 300px;
        overflow-y: auto;
        overflow-x: hidden;
        white-space: nowrap;
        border: none;
    }
</style>
<h1>Lista de usuarios</h1>
<br />
<div class="scrollable-div-u">
    <table class="table table-striped" id="userTable">
        <thead>
            <tr>
                <th>
                    Usuario
                </th>
                <th>
                    Correo eletrónico
                </th>
                <th style="width:10%">
                    Acciones
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td>
                        <div class="row">
                            <div class="col-sm">
                                <a>
                                    @user.UserName
                                </a>
                                <br>
                                <small>
                                    @user.Id
                                </small>

                            </div>
                        </div>
                    </td>
                    <td>
                        <a>
                            @user.Email
                        </a>
                    </td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Acción
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <form asp-action="EliminarUsuario" asp-controller="User" method="post">
                                        <input type="hidden" name="userId" value="@user.Id" />
                                        <button type="submit" class="dropdown-item"><i class="fas fa-trash-alt"></i> Eliminar</button>
                                    </form>
                                </li>
                                <li>
                                    <a style='margin-right:16px' asp-controller="UserRoles" asp-action="Index" asp-route-userId="@user.Id" class="dropdown-item">
                                        <i class="fas fa-wrench"></i> Administrar roles
                                    </a>
                                </li>

                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>